CREATE DATABASE hosting;
USE hosting;
CREATE TABLE DANEOSOBOWE(
	Pesel CHAR(11),
	Imię VARCHAR(20) NOT NULL,
	Nazwisko VARCHAR(30) NOT NULL,
	Data_urodzenia DATE NOT NULL,
	Plec CHAR(1),
	Adres VARCHAR(50),
	PRIMARY KEY (Pesel)
);
CREATE TABLE KONTASERWISU(
	Login VARCHAR(100),
	Haslo VARCHAR(100),
	Data_utworzenia DATE NOT NULL,
	Wlasciciel CHAR(11) DEFAULT NULL,
	OstatnieLogowanie DATETIME,
	PRIMARY KEY (Login),
	FOREIGN KEY (Wlasciciel) REFERENCES DANEOSOBOWE(Pesel)
);
CREATE TABLE Serwery(
	`Host` VARCHAR(100),
	AdresIP VARCHAR(50) NOT NULL UNIQUE,
	NazwaSerwisu VARCHAR(100),
	PRIMARY KEY (`Host`)
);
CREATE TABLE LOGOWANIA(
	ID INT AUTO_INCREMENT,
	Login VARCHAR(100) NOT NULL,
	`Host` VARCHAR(100) NOT NULL,
	AdresIPUzytkownika VARCHAR(50) NOT NULL,
	DataLogowania DATETIME NOT NULL,
	DataWylogowania DATETIME NOT NULL,
	PRIMARY KEY (ID)
);
CREATE TABLE LOGOWANIA_OLD(
	ID INT,
	Login VARCHAR(100) NOT NULL,
	`Host` VARCHAR(100) NOT NULL,
	AdresIPUzytkownika VARCHAR(50) NOT NULL,
	DataLogowania DATETIME NOT NULL,
	DataWylogowania DATETIME NOT NULL,
	PRIMARY KEY (ID)
);