LOAD DATA INFILE 'POKOJE.csv' INTO TABLE `pokoje`
FIELDS TERMINATED BY ',' 
ENCLOSED BY '' 
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;*/
LOAD DATA INFILE 'Rezerwacje.csv' INTO TABLE `rezerwacje`
FIELDS TERMINATED BY ';' 
ENCLOSED BY '' 
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;