LOAD DATA INFILE 'towary.csv' 
INTO TABLE `towary` 
FIELDS TERMINATED BY ';' 
LINES TERMINATED BY '\r\n' 
IGNORE 1 LINES;

LOAD DATA INFILE 'klienci.csv'
INTO TABLE `towary` 
FIELDS TERMINATED BY ';' 
LINES TERMINATED BY '\r\n' 
IGNORE 1 LINES;