ALTER TABLE `Zgloszenia`
ADD COLUMN `idzgloszenia` INT PRIMARY KEY AUTO_INCREMENT = 1;
LOAD DATA LOCAL INFILE 'kandydaci_constraint_error_free.csv' INTO TABLE `kandydaci`
FIELDS TERMINATED BY ', ' 
ENCLOSED BY '' 
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
LOAD DATA LOCAL INFILE 'zgloszenia.csv' INTO TABLE `zgloszenia`
FIELDS TERMINATED BY ', ' 
ENCLOSED BY '' 
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;